version: "3.9"
services:

  owa:
    image: openwa/wa-automate:latest
    hostname: owa
    init: true
    restart: on-failure
    volumes:
      - "sessions:/sessions"
    ports:
      - "8080:8080"
    environment:
      WA_DISABLE_SPINS: 'true' # Example cli config as ENV VAR. Use any flag from https://docs.openwa.dev/docs/configuration/command-line-options and convert to capital snake case with `WA_` prefix
      WA_SESSION_ID: "MY_SESSION" # Change this

volumes:
  sessions: